version: "3.9"

services:
  supabase-db:
    image: supabase/postgres:${SUPABASE_DB_VERSION}
    container_name: supabase-db
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - supabase-db-data:/var/lib/postgresql/data
      - ./migration/complete_setup.sql:/docker-entrypoint-initdb.d/complete_setup.sql

  supabase-api:
    image: postgrest/postgrest:${SUPABASE_API_VERSION}
    container_name: supabase-api
    restart: unless-stopped
    ports:
      - "${SUPABASE_API_PORT}:3000"
    environment:
      PGRST_DB_URI: postgres://${DB_USER}:${DB_PASSWORD}@supabase-db:5432/${DB_NAME}
      PGRST_DB_ANON_ROLE: anon
      PGRST_DB_SCHEMAS: public
      PGRST_DB_EXTRA_SEARCH_PATH: public
      PGRST_JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - supabase-db

  supabase-meta:
    image: supabase/postgres-meta:${SUPABASE_META_VERSION}
    container_name: supabase-meta
    restart: unless-stopped
    ports:
      - "${SUPABASE_META_PORT}:8080"
    environment:
      PG_META_DB_HOST: supabase-db
      PG_META_DB_PORT: 5432
      PG_META_DB_NAME: ${DB_NAME}
      PG_META_DB_USER: ${DB_USER}
      PG_META_DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - supabase-db

  supabase-studio:
    image: supabase/studio:${SUPABASE_STUDIO_VERSION}
    container_name: supabase-studio
    restart: unless-stopped
    ports:
      - "${SUPABASE_STUDIO_PORT}:3000"
    environment:
      SUPABASE_URL: http://supabase-api:3000
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY}
    depends_on:
      - supabase-api

  archon-server:
    build:
      context: ./python
      dockerfile: Dockerfile.server
    container_name: archon-server
    restart: unless-stopped
    ports:
      - "${ARCHON_SERVER_PORT}:8181"
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@supabase-db:5432/${DB_NAME}
    depends_on:
      - supabase-db

  archon-mcp:
    build:
      context: ./python
      dockerfile: Dockerfile.mcp
    container_name: archon-mcp
    restart: unless-stopped
    ports:
      - "${ARCHON_MCP_PORT}:8051"
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@supabase-db:5432/${DB_NAME}
    depends_on:
      - supabase-db

  archon-frontend:
    build:
      context: ./archon-ui-main
      dockerfile: Dockerfile.frontend
    container_name: archon-frontend
    restart: unless-stopped
    ports:
      - "${ARCHON_FRONTEND_PORT}:3737"
    environment:
      VITE_SUPABASE_URL: http://localhost:${SUPABASE_API_PORT}
      VITE_SUPABASE_ANON_KEY: ${ANON_KEY}
    depends_on:
      - supabase-api

volumes:
  supabase-db-data:
    driver: local
