services:
  supabase-db:
    image: supabase/postgres:${SUPABASE_DB_VERSION}
    container_name: supabase-db
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./docker/volumes/db/data:/var/lib/postgresql/data
      - ./complete_setup.sql:/docker-entrypoint-initdb.d/complete_setup.sql

  supabase-api:
    image: postgrest/postgrest:${POSTGREST_VERSION}
    container_name: supabase-api
    restart: unless-stopped
    depends_on:
      - supabase-db
    ports:
      - "${POSTGREST_PORT}:3000"
    environment:
      PGRST_DB_URI: postgres://${DB_USER}:${DB_PASSWORD}@supabase-db:5432/${DB_NAME}
      PGRST_DB_ANON_ROLE: ${DB_ANON_ROLE}
      PGRST_DB_SCHEMA: ${DB_SCHEMA}
      PGRST_SERVER_PORT: 3000

  supabase-meta:
    image: supabase/postgres-meta:${SUPABASE_META_VERSION}
    container_name: supabase-meta
    restart: unless-stopped
    depends_on:
      - supabase-db
    ports:
      - "${POSTGRES_META_PORT}:8080"
    environment:
      PG_META_DB_HOST: supabase-db
      PG_META_DB_PORT: 5432
      PG_META_DB_NAME: ${DB_NAME}
      PG_META_DB_USER: ${DB_USER}
      PG_META_DB_PASSWORD: ${DB_PASSWORD}

  supabase-studio:
    image: supabase/studio:${SUPABASE_STUDIO_VERSION}
    container_name: supabase-studio
    restart: unless-stopped
    depends_on:
      - supabase-db
      - supabase-api
      - supabase-meta
    ports:
      - "${STUDIO_PORT}:3000"
    environment:
      NEXT_PUBLIC_SUPABASE_URL: http://localhost:${POSTGREST_PORT}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}

  archon-server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    container_name: archon-server
    restart: unless-stopped
    ports:
      - "${ARCHON_SERVER_PORT}:8181"
    env_file:
      - .env
    depends_on:
      - supabase-db
      - supabase-api

  archon-mcp:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.mcp
    container_name: archon-mcp
    restart: unless-stopped
    ports:
      - "${MCP_PORT}:8051"
    env_file:
      - .env
    depends_on:
      - supabase-db
      - supabase-api

  archon-frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile.frontend
    container_name: archon-ui
    restart: unless-stopped
    ports:
      - "${ARCHON_UI_PORT}:3737"
    env_file:
      - .env
    depends_on:
      - archon-server
